/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/LDL.hpp>
#include <vector>
#include <time.h>
#include "Isometrc.hpp"

#if (_MSC_VER <= 1200)
    #define STBI_NO_THREAD_LOCALS
    #define STBI_NO_SIMD
#endif

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

const LDL::Vec2i tileSize = LDL::Vec2i(128, 64);
const LDL::Vec2i mapSize  = LDL::Vec2i(7, 7);
const LDL::Vec2i startPos = LDL::Vec2i(400, 50);

int Random(int min, int max)
{
	return min + (rand() % (max - min + 1));
}

int main()
{
	srand((uint32_t)time(NULL));

	LDL::Result result;
	LDL::Window window(result, LDL::Vec2i(0, 0), LDL::Vec2i(800, 600));
	LDL::Render render(result, window);
    LDL::Event  report;

	stbi_set_flip_vertically_on_load(true);

	int width, height, channels;
	unsigned char* pixels = stbi_load("SeasonsTiles.png", &width, &height, &channels, STBI_default);
	LDL::Texture tiles(result, render, LDL::Vec2i(width, height), channels, pixels, LDL::Color(0, 0, 0));
	stbi_image_free(pixels);

	Isometric isometric;

	std::vector<int> tilesX;
	std::vector<int> tilesY;

	tilesX.resize(mapSize.x * mapSize.y);
	tilesY.resize(mapSize.x * mapSize.y);

	for (size_t i = 0; i < mapSize.x * mapSize.y; i++)
	{
		tilesX[i] = Random(0, 7);
		tilesY[i] = Random(0, 5);
	}
	
	while (window.Running())
	{
		while (window.GetEvent(report))
		{
			if (report.Type == LDL::Event::IsQuit)
			{
				window.StopEvent();
			}
		}

		render.Begin();

		size_t j = 0;

		for (size_t rows = 0; rows < mapSize.x; rows++)
		{
			for (size_t cols = 0; cols < mapSize.y; cols++)
			{
				int x = (int)cols * tileSize.x / 2;
				int y = (int)rows * tileSize.y;

				LDL::Vec2i pt = isometric.CartesianToIsometric(LDL::Vec2i(x, y));

				int tx = tileSize.x * tilesX[j];
				int ty = tileSize.y * tilesY[j];
				j++;

				render.Draw(&tiles, LDL::Vec2i(startPos.x + pt.x, startPos.y + pt.y), tileSize, LDL::Vec2i(tx, ty), tileSize);
			}
		}

		render.End();

		window.Update();
		window.PollEvents();
	}

    return 0;
}
