/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef libc_stdint_h
#define libc_stdint_h

#if defined(_WIN64)
    typedef unsigned long long uintmax_t;
    typedef signed long long   intmax_t;
#elif defined(_WIN32)
    typedef unsigned int uintmax_t;
    typedef signed int   intmax_t;
#else
    typedef unsigned long long uintmax_t;
    typedef signed long long   intmax_t;
#endif

#if defined(_BITS_STDINT_INTN_H)
    #include <bits/stdint-intn.h>
    #include <bits/stdint-uintn.h>
#else
    typedef unsigned char      uint8_t;
    typedef signed char        int8_t;

    typedef unsigned short     uint16_t;
    typedef signed short       int16_t;

    typedef unsigned int       uint32_t; 
    typedef signed int         int32_t;

    typedef uintmax_t          uint64_t;
    typedef intmax_t           int64_t;
#endif

#endif
