/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Events_hpp
#define LDL_Events_hpp

#include <stdint.h>
#include <LDL/Enums.hpp>

namespace LDL
{
	class EventQuit
	{
	public:
		uint8_t Type;
	};

	class EventMouse
	{
	public:
		uint8_t Type;
		uint8_t State;
		uint8_t Button;
		int     PosX;
		int     PosY;
		int     Scroll;
		int     Delta;
	};

	class EventResize
	{
	public:
		uint8_t Type;
		int     Width;
		int     Height;
	};

	class EventKeyboard
	{
	public:
		uint8_t Type;
		uint8_t State;
		uint8_t Key;
	};

	class EventGainedFocus
	{
	public:
		uint8_t Type;
	};

	class EventLostFocus
	{
	public:
		uint8_t Type;
	};

	class Event
	{
	public:
		enum
		{
			IsQuit = 1,
			IsMouseMove,
			IsMouseClick,
			IsResize,
			IsKeyboard,
			IsGainedFocus,
			IsLostFocus,
			IsMouseScroll
		};

		union
		{
			uint8_t          Type;
			EventQuit        Quit;
			EventMouse       Mouse;
			EventResize      Resize;
			EventKeyboard    Keyboard;
			EventGainedFocus GainedFocus;
			EventLostFocus   LostFocus;
		};

		bool IsKeyPressed(uint8_t key)
		{
			return (Type == IsKeyboard && Keyboard.Key == key && Keyboard.State == ButtonState::Pressed);
		}

		bool IsKeyReleased(uint8_t key)
		{
			return (Type == IsKeyboard && Keyboard.Key == key && Keyboard.State == ButtonState::Released);
		}

		bool IsMousePressed(uint8_t key)
		{
			return (Type == IsMouseClick && Mouse.Button == key && Mouse.State == ButtonState::Pressed);
		}

		bool IsMouseReleased(uint8_t key)
		{
			return (Type == IsMouseClick && Mouse.Button == key && Mouse.State == ButtonState::Released);
		}
	private:
	};
}

#endif
