/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef WinAPI_Consts_hpp
#define WinAPI_Consts_hpp

const DWORD STD_INPUT_HANDLE  = ((DWORD)-10);
const DWORD STD_OUTPUT_HANDLE = ((DWORD)-11);
const DWORD STD_ERROR_HANDLE  = ((DWORD)-12);

const DWORD CREATE_NEW        = 1;
const DWORD CREATE_ALWAYS     = 2;
const DWORD OPEN_EXISTING     = 3;
const DWORD OPEN_ALWAYS       = 4;
const DWORD TRUNCATE_EXISTING = 5;

const DWORD GENERIC_READ    = (0x80000000L);
const DWORD GENERIC_WRITE   = (0x40000000L);
const DWORD GENERIC_EXECUTE = (0x20000000L);
const DWORD GENERIC_ALL     = (0x10000000L);

const DWORD FILE_ATTRIBUTE_NORMAL = 0x00000080;

const UINT CS_VREDRAW         = 0x0001;
const UINT CS_HREDRAW         = 0x0002;
const UINT CS_DBLCLKS         = 0x0008;
const UINT CS_OWNDC           = 0x0020;
const UINT CS_CLASSDC         = 0x0040;
const UINT CS_PARENTDC        = 0x0080;
const UINT CS_NOCLOSE         = 0x0200;
const UINT CS_SAVEBITS        = 0x0800;
const UINT CS_BYTEALIGNCLIENT = 0x1000;
const UINT CS_BYTEALIGNWINDOW = 0x2000;
const UINT CS_GLOBALCLASS     = 0x4000;

const DWORD WS_OVERLAPPED   = 0x00000000L;
const DWORD WS_POPUP        = 0x80000000L;
const DWORD WS_CHILD        = 0x40000000L;
const DWORD WS_MINIMIZE     = 0x20000000L;
const DWORD WS_VISIBLE      = 0x10000000L;
const DWORD WS_DISABLED     = 0x08000000L;
const DWORD WS_CLIPSIBLINGS = 0x04000000L;
const DWORD WS_CLIPCHILDREN = 0x02000000L;
const DWORD WS_MAXIMIZE     = 0x01000000L;
const DWORD WS_CAPTION      = 0x00C00000L;
const DWORD WS_BORDER       = 0x00800000L;
const DWORD WS_DLGFRAME     = 0x00400000L;
const DWORD WS_VSCROLL      = 0x00200000L;
const DWORD WS_HSCROLL      = 0x00100000L;
const DWORD WS_SYSMENU      = 0x00080000L;
const DWORD WS_THICKFRAME   = 0x00040000L;
const DWORD WS_GROUP        = 0x00020000L;
const DWORD WS_TABSTOP      = 0x00010000L;
const DWORD WS_MINIMIZEBOX  = 0x00020000L;
const DWORD WS_MAXIMIZEBOX  = 0x00010000L;
const DWORD WS_TILED        = WS_OVERLAPPED;
const DWORD WS_ICONIC       = WS_MINIMIZE;
const DWORD WS_SIZEBOX      = WS_THICKFRAME;
const DWORD WS_OVERLAPPEDWINDOW = (WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX);
const DWORD WS_POPUPWINDOW  = (WS_POPUP | WS_BORDER | WS_SYSMENU);
const DWORD WS_TILEDWINDOW  = WS_OVERLAPPEDWINDOW;

const int SW_HIDE            = 0;
const int SW_SHOWNORMAL      = 1;
const int SW_NORMAL          = 1;
const int SW_SHOWMINIMIZED   = 2;
const int SW_SHOWMAXIMIZED   = 3;
const int SW_MAXIMIZE        = 3;
const int SW_SHOWNOACTIVATE  = 4;
const int SW_SHOW            = 5;
const int SW_MINIMIZE        = 6;
const int SW_SHOWMINNOACTIVE = 7;
const int SW_SHOWNA          = 8;
const int SW_RESTORE         = 9;
const int SW_SHOWDEFAULT     = 10;
const int SW_FORCEMINIMIZE   = 11;
const int SW_MAX             = 11;

const UINT WM_NULL     = 0x0000;
const UINT WM_CREATE   = 0x0001;
const UINT WM_DESTROY  = 0x0002;
const UINT WM_MOVE     = 0x0003;
const UINT WM_SIZE     = 0x0005;
const UINT WM_ACTIVATE = 0x0006;
const UINT WM_CLOSE    = 0x0010;

const ULONG_PTR COLOR_SCROLLBAR           = 0;
const ULONG_PTR COLOR_BACKGROUND          = 1;
const ULONG_PTR COLOR_ACTIVECAPTION       = 2;
const ULONG_PTR COLOR_INACTIVECAPTION     = 3;
const ULONG_PTR COLOR_MENU                = 4;
const ULONG_PTR COLOR_WINDOW              = 5;
const ULONG_PTR COLOR_WINDOWFRAME         = 6;
const ULONG_PTR COLOR_MENUTEXT            = 7;
const ULONG_PTR COLOR_WINDOWTEXT          = 8;
const ULONG_PTR COLOR_CAPTIONTEXT         = 9;
const ULONG_PTR COLOR_ACTIVEBORDER        = 10;
const ULONG_PTR COLOR_INACTIVEBORDER      = 11;
const ULONG_PTR COLOR_APPWORKSPACE        = 12;
const ULONG_PTR COLOR_HIGHLIGHT           = 13;
const ULONG_PTR COLOR_HIGHLIGHTTEXT       = 14;
const ULONG_PTR COLOR_BTNFACE             = 15;
const ULONG_PTR COLOR_BTNSHADOW           = 16;
const ULONG_PTR COLOR_GRAYTEXT            = 17;
const ULONG_PTR COLOR_BTNTEXT             = 18;
const ULONG_PTR COLOR_INACTIVECAPTIONTEXT = 19;
const ULONG_PTR COLOR_BTNHIGHLIGHT        = 20;

const int GWLP_USERDATA = -21;
const int GWL_USERDATA  = -21;

const UINT PM_REMOVE = 0x0001;

#endif
