/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef WinAPI_Types_hpp
#define WinAPI_Types_hpp

#include <stddef.h>
#include <stdint.h>

typedef void* LPVOID;
typedef void* PVOID;
typedef intmax_t   LONG_PTR;
typedef uintmax_t  ULONG_PTR;
typedef uint32_t   DWORD;
typedef int32_t    LONG;
typedef uint8_t    BYTE;

typedef DWORD      COLORREF;
typedef DWORD* LPCOLORREF;

typedef LPVOID     HGDIOBJ;
typedef LPVOID     HANDLE;
typedef LPVOID     HWND;
typedef LPVOID     HINSTANCE;
typedef LPVOID     HICON;
typedef LPVOID     HCURSOR;
typedef LPVOID     HBRUSH;
typedef LPVOID     HMENU;
typedef LPVOID     HMODULE;
typedef LPVOID     HDC;

typedef DWORD      UINT_PTR;
typedef UINT_PTR   WPARAM;
typedef LONG_PTR   LPARAM;
typedef LONG_PTR   LRESULT;
typedef DWORD      UINT;
typedef DWORD* LPDWORD;
typedef ULONG_PTR  SIZE_T;
typedef ULONG_PTR  DWORD_PTR;
typedef DWORD      BOOL;
typedef DWORD      UINT;
typedef DWORD      WORD;
typedef WORD       ATOM;

typedef char CHAR;
typedef const CHAR* LPCSTR, * PCSTR;

typedef LRESULT(WINAPI* WNDPROC)(HWND, UINT, WPARAM, LPARAM);

#endif
