/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/Windows/MainWin.hpp>
#include <string.h>

using namespace LDL;

MainWindow::MainWindow(Result& result, const Vec2i& pos, const Vec2i& size) :
    _baseWindow(pos, size, ""),
	_hwnd(NULL),
	_hdc(NULL),
	_result(result)
{
    memset(&_message,     0, sizeof(MSG));
    memset(&_windowClass, 0, sizeof(WNDCLASSA));

	_windowClass.style         = CS_HREDRAW | CS_VREDRAW;
	_windowClass.cbClsExtra    = 0;
	_windowClass.cbWndExtra    = 0;
	_windowClass.lpszClassName = "Window";
	_windowClass.hInstance     = GetModuleHandle(NULL);
	_windowClass.hbrBackground = (HBRUSH)COLOR_APPWORKSPACE;
	_windowClass.lpszMenuName  = NULL;
	_windowClass.lpfnWndProc   = WndProc;

	if (RegisterClass(&_windowClass) == NULL)
	{
		_result.Message(_windowError.GetErrorMessage());
	}
	else
	{
		int x = _baseWindow.Pos().x;
		int y = _baseWindow.Pos().y;
		int w = _baseWindow.Size().x;
		int h = _baseWindow.Size().y;

		_hwnd = CreateWindow(_windowClass.lpszClassName, "", WS_OVERLAPPEDWINDOW | WS_VISIBLE, x, y, w, h, NULL, NULL, _windowClass.hInstance, NULL);

		if (_hwnd == NULL)
		{
			_result.Message(_windowError.GetErrorMessage());
		}
		else
		{
			_hdc = GetDC(_hwnd);

			if (_hdc == NULL)
			{
				_result.Message(_windowError.GetErrorMessage());
			}
			else
			{
#if defined(_WIN64)
				SetWindowLongPtr(_hwnd, GWLP_WNDPROC, (LONG_PTR)WndProc);
				SetWindowLongPtr(_hwnd, GWLP_USERDATA, (LONG_PTR)this);
#elif defined(_WIN32)
				SetWindowLong(_hwnd, GWL_WNDPROC, (LONG)WndProc);
				SetWindowLong(_hwnd, GWL_USERDATA, (LONG)this);
#endif  
			}
		}
	}
}

MainWindow::~MainWindow()
{
	if (UnregisterClass(_windowClass.lpszClassName, _windowClass.hInstance) == FALSE)
	{
		_result.Message(_windowError.GetErrorMessage());
	}
	else
	{
		if (ReleaseDC(_hwnd, _hdc) == 0)
		{
			_result.Message(_windowError.GetErrorMessage());
		}
	}
}

const Vec2i& MainWindow::Pos()
{
	return _baseWindow.Pos();
}

void MainWindow::Pos(const Vec2i& pos)
{
	_baseWindow.Pos(pos);
}

const Vec2i& MainWindow::Size()
{
	return _baseWindow.Size();
}

void MainWindow::Size(const Vec2i& size)
{
	_baseWindow.Size(size);
}

const std::string& MainWindow::Title()
{
	return _baseWindow.Title();
}

void MainWindow::Title(const std::string& title)
{
	_baseWindow.Title(title);
}

void MainWindow::Update()
{
	if (ShowWindow(_hwnd, SW_SHOW) == FALSE)
	{
		_result.Message(_windowError.GetErrorMessage());
	}
	else
	{
		if (UpdateWindow(_hwnd) == FALSE)
		{
			_result.Message(_windowError.GetErrorMessage());
		}
	}
}

void MainWindow::StopEvent()
{
	_eventer.Stop();
}

bool MainWindow::Running()
{
	return _eventer.Running();
}

void MainWindow::PollEvents()
{
	while (PeekMessage(&_message, _hwnd, 0, 0, PM_REMOVE))
	{
		TranslateMessage(&_message);
		DispatchMessage(&_message);
	}
}

bool MainWindow::GetEvent(Event& event)
{
	if (!_eventer.Empty())
	{
		_eventer.Pop(event);

		return true;
	}

	return false;
}

LRESULT CALLBACK MainWindow::Handler(UINT Message, WPARAM WParam, LPARAM LParam)
{
	Event event;

	switch (Message)
	{

	case WM_DESTROY:
		PostQuitMessage(0);
		break;

	case WM_CLOSE:
		event.Type = Event::IsQuit;
		_eventer.Push(event);
		break;

	case WM_ERASEBKGND:
		break;

	case WM_PALETTECHANGED:
		break;
	}

	return DefWindowProc(_hwnd, Message, WParam, LParam);
}

LRESULT CALLBACK MainWindow::WndProc(HWND Hwnd, UINT Message, WPARAM WParam, LPARAM LParam)
{
	LRESULT result;

#if defined(_WIN64)
	MainWindow* This = (MainWindow*)GetWindowLongPtr(Hwnd, GWLP_USERDATA);
#elif defined(_WIN32)
	MainWindow* This = (MainWindow*)GetWindowLong(Hwnd, GWL_USERDATA);
#endif  

	if (This != NULL)
	{
		result = This->Handler(Message, WParam, LParam);
	}
	else
	{
		result = DefWindowProc(Hwnd, Message, WParam, LParam);
	}

	return result;
}

const HWND MainWindow::Hwnd()
{
	return _hwnd;
}

const HDC MainWindow::Hdc()
{
	return _hdc;
}
