/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <string.h>
#include <assert.h>
#include <LDL/Win16/GdiRndr.hpp>
#include <LDL/Win16/GdiUtils.hpp>

using namespace LDL;

GdiRender::GdiRender(Result& result, MainWindow& window) :
	_window(window),
	_result(result)
{
}

GdiRender::GdiRender(Result& result, MainWindow& window, const Palette& palette) :
	_window(window),
	_palette(palette),
	_result(result)
{
}

GdiRender::~GdiRender()
{
}

const Palette& GdiRender::GetPalette()
{
	return _palette;
}

const Color& GdiRender::GetColor()
{
	return _baseRender.GetColor();
}

void GdiRender::SetColor(uint8_t index)
{
	return _baseRender.SetColor(index);
}
void GdiRender::SetColor(const Color& color)
{
	_baseRender.SetColor(color);
}

void GdiRender::Begin()
{
	InvalidateRect(_window.Hwnd(), NULL, FALSE);
}

void GdiRender::End()
{
}

void GdiRender::Clear()
{
	Fill(Vec2i(0, 0), _window.Size());
}

void GdiRender::Line(const Vec2i& first, const Vec2i& last)
{
	MoveToEx(_window.Hdc(), first.x, first.y, NULL);
	LineTo(_window.Hdc(), last.x, last.y);
}

void GdiRender::Fill(const Vec2i& pos, const Vec2i& size)
{
	GdiFill(_window.Hdc(), pos, size, _baseRender.GetColor());
}

void GdiRender::Draw(GdiTexture* texture, const Vec2i& dstPos, const Vec2i& dstSize, const Vec2i& srcPos, const Vec2i& srcSize)
{
	assert(texture != NULL);

	HDC hdcm = CreateCompatibleDC(_window.Hdc());

	if (hdcm == NULL)
	{
		_result.Message(_windowError.GetErrorMessage());
	}
	else
	{
		HGDIOBJ object = SelectObject(hdcm, texture->Bitmap());

		if (object == NULL)
		{
			_result.Message(_windowError.GetErrorMessage());
		}
		else
		{
			if (texture->GetColorKey().Used())
			{
				Color color = texture->GetColorKey().GetColor();

				//if (TransparentBlt(_window.Hdc(), dstPos.x, dstPos.y, dstSize.x, dstSize.y, hdcm, srcPos.x, srcPos.y, srcSize.x, srcSize.y, RGB(color.r, color.g, color.b)) == FALSE)
				//{
				//	_result.Message(_windowError.GetErrorMessage());
				//}
			}
			else
			{
				if (StretchBlt(_window.Hdc(), dstPos.x, dstPos.y, dstSize.x, dstSize.y, hdcm, srcPos.x, srcPos.y, srcSize.x, srcSize.y, SRCCOPY) == FALSE)
				{
					_result.Message(_windowError.GetErrorMessage());
				}
			}

			DeleteDC(hdcm);
		}
	}
}

void GdiRender::Draw(GdiTexture* texture, const Vec2i& pos)
{
	Draw(texture, pos, texture->Size(), Vec2i(0, 0), texture->Size());
}

void GdiRender::Draw(GdiTexture* texture, const Vec2i& pos, const Vec2i& size)
{
	Draw(texture, pos, size, Vec2i(0, 0), texture->Size());
}

const HDC GdiRender::Hdc()
{
	return _window.Hdc();
}
