/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <assert.h>
#include <string.h>
#include <LDL/Win16/GdiUtils.hpp>
#include <LDL/Vec2.hpp>

HBITMAP LDL::CreateDib(HDC hdc, const Vec2i& size, uint8_t bpp, void** pixels)
{
    BITMAPINFO bitmapInfo;
    memset(&bitmapInfo, 0, sizeof(BITMAPINFO));

    bitmapInfo.bmiHeader.biSize          = sizeof(BITMAPINFOHEADER);
    bitmapInfo.bmiHeader.biWidth         = size.x;
    bitmapInfo.bmiHeader.biHeight        = size.y;
    bitmapInfo.bmiHeader.biPlanes        = 1;
    bitmapInfo.bmiHeader.biBitCount      = bpp * 8;
    bitmapInfo.bmiHeader.biCompression   = BI_RGB;
    bitmapInfo.bmiHeader.biSizeImage     = size.x * size.x * bpp;
    bitmapInfo.bmiHeader.biXPelsPerMeter = 96;
    bitmapInfo.bmiHeader.biYPelsPerMeter = 96;
    bitmapInfo.bmiHeader.biClrUsed       = 0;
    bitmapInfo.bmiHeader.biClrImportant  = 0;

    return CreateDIBitmap(hdc, &bitmapInfo.bmiHeader, CBM_INIT, pixels, &bitmapInfo, DIB_RGB_COLORS);
}

HBITMAP LDL::CreateDib(HDC hdc, const Vec2i& size, const Palette& palette, void** pixels)
{
    BITMAPINFO bitmapInfo;
    memset(&bitmapInfo, 0, sizeof(BITMAPINFO));

    bitmapInfo.bmiHeader.biSize          = sizeof(BITMAPINFOHEADER);
    bitmapInfo.bmiHeader.biWidth         = size.x;
    bitmapInfo.bmiHeader.biHeight        = size.y;
    bitmapInfo.bmiHeader.biPlanes        = 1;
    bitmapInfo.bmiHeader.biBitCount      = 8;
    bitmapInfo.bmiHeader.biCompression   = BI_RGB;
    bitmapInfo.bmiHeader.biSizeImage     = size.x * size.x;
    bitmapInfo.bmiHeader.biXPelsPerMeter = 96;
    bitmapInfo.bmiHeader.biYPelsPerMeter = 96;
    bitmapInfo.bmiHeader.biClrUsed       = 0;
    bitmapInfo.bmiHeader.biClrImportant  = 0;

    return CreateDIBitmap(hdc, &bitmapInfo.bmiHeader, 0, pixels, &bitmapInfo, DIB_RGB_COLORS);
}

void LDL::DestroyDib(HBITMAP bitmap)
{
    assert(bitmap != NULL);

    DeleteObject(bitmap);
}

void LDL::GdiFill(GdiPalette& dst, const Palette& src)
{
    dst.logPalette.palVersion    = 0x300;
    dst.logPalette.palNumEntries = Palette::Max;

    for (size_t i = 0; i < Palette::Max; i++)
    {
        dst.paletteEntry[i].peRed   = src.Get(i).r;
        dst.paletteEntry[i].peGreen = src.Get(i).g;
        dst.paletteEntry[i].peBlue  = src.Get(i).b;
        dst.paletteEntry[i].peFlags = 0;
    }
}

void LDL::GdiFill(HDC hdc, const Vec2i& pos, const Vec2i& size, const Color& color)
{
    RECT rect;
    
    rect.left   = pos.x;
    rect.top    = pos.y;
    rect.right  = size.x;
    rect.bottom = size.y;
    
    HBRUSH brush = CreateSolidBrush(RGB(color.r, color.g, color.b));

    FillRect(hdc, &rect, brush);

    DeleteObject(brush);

}

void LDL::GdiFill(HDC hdc, const Vec2i& pos, const Vec2i& size, HPALETTE palette, uint8_t index)
{
    RECT rect;

    rect.left   = pos.x;
    rect.top    = pos.y;
    rect.right  = size.x;
    rect.bottom = size.y;

    HDC hdcm = CreateCompatibleDC(hdc);
    SelectPalette(hdc, palette, TRUE);
    RealizePalette(hdc);

    HBRUSH brush = CreateSolidBrush(PALETTEINDEX(index));

    FillRect(hdc, &rect, brush);
    DeleteObject(brush);
    DeleteDC(hdcm);
}

void LDL::GdiLine(HDC hdc, const Vec2i& first, const Vec2i& last, const Color& color)
{
    MoveToEx(hdc, first.x, first.y, NULL);
    LineTo(hdc, last.x, last.y);
}

void LDL::GdiLine(Result& result, WindowError& winError, HDC hdc, const Vec2i& first, const Vec2i& last, uint8_t index)
{
    if (MoveToEx(hdc, first.x, first.y, NULL) == FALSE)
    {
        result.Message(winError.GetErrorMessage());
    }
    else
    {
        if (LineTo(hdc, last.x, last.y) == FALSE)
        {
            result.Message(winError.GetErrorMessage());
        }
    }
}

void LDL::GdiLine(HDC hdc, const Vec2i& first, const Vec2i& last, uint8_t index)
{
    MoveToEx(hdc, first.x, first.y, NULL);
    LineTo(hdc, last.x, last.y);
}
