/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <string.h>
#include <LDL/UNIX/XLib/XLibWin.hpp>

using namespace LDL;

const size_t eventMask =
    PointerMotionMask
  | ButtonMotionMask
  | ButtonPressMask
  | ButtonReleaseMask
  | KeyPressMask
  | KeyReleaseMask;

XLibWindow::XLibWindow(Result& result, const Vec2i& pos, const Vec2i& size) :
    _baseWindow(pos, size, ""),
	_result(result),
	_eventMask(eventMask)
{	
	_display = XOpenDisplay(NULL);

	if (_display == NULL)
	{
		_result.Message("XOpenDisplay failed");
	}
	else
	{
	    _screen  = XDefaultScreen(_display);
	    _root    = XRootWindow(_display, _screen);

		int x = _baseWindow.Pos().x;
		int y = _baseWindow.Pos().y;
		int w = _baseWindow.Size().x;
		int h = _baseWindow.Size().y;

        int border     = BlackPixel(_display, _screen);
		int background = WhitePixel(_display, _screen);

        _window  = XCreateSimpleWindow(_display, _root, x, y, w, h, 1, border, background);
		
		XSelectInput(_display, _window, _eventMask);

        XMapWindow(_display, _window);
	}
}

XLibWindow::~XLibWindow()
{
    XCloseDisplay(_display);
}

const Vec2i& XLibWindow::Pos()
{
	return _baseWindow.Pos();
}

void XLibWindow::Pos(const Vec2i& pos)
{
	_baseWindow.Pos(pos);
}

const Vec2i& XLibWindow::Size()
{
	return _baseWindow.Size();
}

void XLibWindow::Size(const Vec2i& size)
{
	_baseWindow.Size(size);
}

const std::string& XLibWindow::Title()
{
	return _baseWindow.Title();
}

void XLibWindow::Title(const std::string& title)
{
	_baseWindow.Title(title);
}

void XLibWindow::Update()
{
}

void XLibWindow::StopEvent()
{
	_eventer.Stop();
}

bool XLibWindow::Running()
{
	return _eventer.Running();
}

void XLibWindow::PollEvents()
{
	XEvent event;
	size_t key = 0;

	while (XPending(_display))
	{
		XNextEvent(_display, &event);
	}
}

bool XLibWindow::GetEvent(Event& event)
{
	if (!_eventer.Empty())
	{
		_eventer.Pop(event);

		return true;
	}

	return false;
}

Display* XLibWindow::GetXDisplay()
{
    return _display;
}

int XLibWindow::GetXScreen()
{
    return _screen;
}

Window XLibWindow::GetXRoot()
{
    return _root;
}

Window XLibWindow::GetXWindow()
{
    return _window;
}
