/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_UNIX_XLib_XLibRndr_hpp
#define LDL_UNIX_XLib_XLibRndr_hpp

#include <LDL/UNIX/XLib/XLibWin.hpp>
#include <LDL/UNIX/XLib/XLibTex.hpp>
#include <LDL/BaseRndr.hpp>
#include <LDL/Palette.hpp>

namespace LDL
{
	class XLibTexture;

	class XLibRender
	{
	public:
	
		XLibRender(Result& result, XLibWindow& window);
		XLibRender(Result& result, XLibWindow& window, const Palette& palette);
		~XLibRender();
		const Color& GetColor();
		void SetColor(const Color& color);
		void Begin();
		void End();
		void Clear();
		void Line(const Vec2i& first, const Vec2i& last);
		void Fill(const Vec2i& pos, const Vec2i& size);
		void Draw(XLibTexture* texture, const Vec2i& dstPos, const Vec2i& dstSize, const Vec2i& srcPos, const Vec2i& srcSize);
		void Draw(XLibTexture* texture, const Vec2i& pos);
		void Draw(XLibTexture* texture, const Vec2i& pos, const Vec2i& size);
		Display* GetXDisplay();
		Visual* GetXVisual();
		int GetXDepth();
	private:
		XLibWindow& _window;
		GC          _graphics;
		BaseRender  _baseRender;
		Result&     _result;
		Palette     _palette;
		int         _depth;
		Visual*     _visual;
		XGCValues   _values;
	};
}

#endif
